version: "2.0"

volumes:
  postgres-data:

services:
  server:
    container_name: chat_bot.prod.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN:?TOKEN is unset}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is unset}
      DB_HOST: ${DB_HOST:-localhost}
    restart: on-failure


  postgres:
    image: postgres:12.1-alpine
    container_name: chat_bot.prod.postgres
    ports:
      - "127.0.0.1:5432:5432"
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is unset}
      POSTGRES_DB: ${POSTGRES_DB:-ChatBot_p2_delivery}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
